language: node_js
node_js:
  - "node"
script:
  - npm run build
  - npm run test
branches:
  only:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
